[versions]
kotlinVersion = "1.9.20"
ksp-version = "1.9.20-1.0.14"
googleServicesVersion = "4.4.0"
firebase-appdistribution-gradle = "4.0.1"
firebaseCrashlytics = "2.9.9"
firebase-perf-plugin = "1.4.2"
junit = "1.1.5"
android-gradle-plugin = "8.2.0"
hiltVersion = "2.48.1"
hilt-navigation-compose = "1.1.0"
activityCompose = "1.8.1"
core-ktx = "1.12.0"
lifecycleRuntimeCompose = "2.6.2"
navigationCompose = "2.7.5"
roomVersion = "2.6.1"
composeBomVersion = "2023.10.01"
firebaseBomVersion = "32.6.0"
jUnit4Version = "4.13.2"
uiTestJunit4 = "1.5.4"

####################################################################################################

[libraries]
# Top-level `build.gradle.kts` file
google-services = { module = "com.google.gms:google-services", version.ref = "googleServicesVersion" }
firebase-appdistribution-gradle = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebase-appdistribution-gradle" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlytics" }
firebase-perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "firebase-perf-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }

# Core
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
debug-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-perf = { module = "com.google.firebase:firebase-perf-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }

# Room
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

# Testing
junit4 = { module = "junit:junit", version.ref = "jUnit4Version" }
junit4-androidx = { module = "androidx.test.ext:junit", version.ref = "junit" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }

####################################################################################################

[bundles]
core = ["core-ktx", "lifecycle-runtime-compose", "activity-compose", "lifecycle-viewmodel-compose", "navigation-compose"]
hilt = ["hilt-android", "hilt-navigation-compose"]
room = ["room-ktx", "room-runtime"]
compose = ["compose-ui", "compose-ui-preview", "compose-material3"]
compose-debug = ["debug-compose-ui-tooling", "debug-compose-ui-test-manifest"]
firebase = ["firebase-analytics", "firebase-crashlytics", "firebase-perf", "firebase-auth", "firebase-firestore"]
junit4 = ["junit4-androidx", "ui-test-junit4"]

####################################################################################################

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics"}
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }